# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-17 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lisense_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('lisense_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('consist', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('id_medic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab2.Medic')),
                ('id_ph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab2.Pharmacy')),
            ],
        ),
    ]
